
# tap repositories and their packages

tap homebrew/core
brew ansible
brew autoconf
brew brotli
brew btop
brew c-ares
brew ca-certificates
brew certifi
brew cffi
brew coreutils
brew cryptography
brew docker
brew docker-completion
brew fzf
brew gettext
brew git
brew gmp
brew gnu-sed
brew grep
brew helm
brew icu4c@75
brew icu4c@77
brew iproute2mac
brew jq
brew k9s
brew krb5
brew kubernetes-cli
brew kubetail --with-short-names
brew libevent
brew libnghttp2
brew libsodium
brew libssh
brew libuv
brew libvterm
brew libyaml
brew lpeg
brew luajit
brew luv
brew lz4
brew m4
brew marp-cli
brew minikube
brew mpdecimal
brew msgpack
brew ncurses
brew neovim
brew node
brew nvm
brew oniguruma
brew openssl@3
brew pcre2
brew pipx
brew pkgconf
brew podman
brew postgresql@14
brew pycparser
brew pyenv
brew python@3.13
brew pyyaml
brew readline
brew sqlite
brew stow
brew telnet
brew tmux
brew tree
brew tree-sitter
brew unibilium
brew utf8proc
brew vault
brew watch
brew xz
brew yq
brew zlib
brew zsh-autosuggestions

tap homebrew/cask
cask 1password
cask betterdisplay
cask chromium
cask docker
cask drawio
cask firefox
cask firefox@nightly
cask floorp
cask font-hack-nerd-font
cask ghostty
cask gimp
cask google-drive
cask hiddenbar
cask iina
cask iterm2
cask jetbrains-toolbox
cask karabiner-elements
cask mac-mouse-fix@2
cask messenger
cask microsoft-remote-desktop
cask obsidian
cask openlens
cask openmtp
cask podman-desktop
cask postman
cask rectangle
cask slack
cask spotify
cask teamviewer
cask virtualbox
cask visual-studio-code
cask vlc
cask whatsapp
cask zen

tap felixkratz/formulae
brew borders
brew sketchybar

tap hashicorp/tap

tap johanhaleby/kubetail

tap nikitabobko/tap
cask aerospace

tap rcmdnk/file
brew brew-file

tap sdkman/tap
brew sdkman-cli

# App Store applications
appstore 1474276998 HP Smart (18.6.1)
appstore 803453959 Slack (4.44.59)
appstore 1278508951 Trello (2.15.9)
appstore 6450432292 Universal Print (1.0)
